const CHINA_TIME_OFFSET_MS = 8 * 60 * 60 * 1000;
const HOME_CACHE_TTL_MS = 60 * 1000;
const PROFILE_CACHE_TTL_MS = 60 * 1000;
const STATIC_DATA_CACHE_TTL_MS = 60 * 1000;
const WITHDRAW_RECORDS_CACHE_TTL_MS = 30 * 1000;
const PAYMENT_INFO_CACHE_TTL_MS = 30 * 1000;
const NOTIFICATIONS_CACHE_TTL_MS = 30 * 1000;
const MINIAPP_LIST_PAGE_SIZE = 20;

const LOGIN_FAILURE_LIMIT = 3;
const LOGIN_COOLDOWN_MS = 60 * 1000;

module.exports = {
  CHINA_TIME_OFFSET_MS,
  HOME_CACHE_TTL_MS,
  LOGIN_COOLDOWN_MS,
  LOGIN_FAILURE_LIMIT,
  MINIAPP_LIST_PAGE_SIZE,
  NOTIFICATIONS_CACHE_TTL_MS,
  PAYMENT_INFO_CACHE_TTL_MS,
  PROFILE_CACHE_TTL_MS,
  STATIC_DATA_CACHE_TTL_MS,
  WITHDRAW_RECORDS_CACHE_TTL_MS,
};
