const CHINA_TIME_OFFSET_MS = 8 * 60 * 60 * 1000;
const HOME_CACHE_TTL_MS = 60 * 1000;
const PROFILE_CACHE_TTL_MS = 60 * 1000;
const STATIC_DATA_CACHE_TTL_MS = 60 * 1000;
const MINIAPP_LIST_PAGE_SIZE = 20;

const WITHDRAW_DAILY_LIMIT = 1;
const WITHDRAW_MIN_AMOUNT_CENTS = 100;
const WITHDRAW_SUBMIT_START_HOUR = 9;
const WITHDRAW_SUBMIT_END_HOUR = 18;

const LOGIN_FAILURE_LIMIT = 3;
const LOGIN_COOLDOWN_MS = 30 * 1000;

module.exports = {
  CHINA_TIME_OFFSET_MS,
  HOME_CACHE_TTL_MS,
  LOGIN_COOLDOWN_MS,
  LOGIN_FAILURE_LIMIT,
  MINIAPP_LIST_PAGE_SIZE,
  PROFILE_CACHE_TTL_MS,
  STATIC_DATA_CACHE_TTL_MS,
  WITHDRAW_DAILY_LIMIT,
  WITHDRAW_MIN_AMOUNT_CENTS,
  WITHDRAW_SUBMIT_END_HOUR,
  WITHDRAW_SUBMIT_START_HOUR,
};
